(PE-33645) Pin apacheds-core-avl for Java 11
When running tests on Java 11, we were getting the following error:
```
Uncaught exception in test fixture
expected: nil
  actual: java.lang.NoClassDefFoundError: sun/reflect/Reflection
   at org.apache.directory.server.core.avltree.ArrayMarshaller.deserialize (ArrayMarshaller.java:153)
   [...]
```
This commit adds an explicit dependency on apacheds-core-avl 1.5.6, as suggested
by https://github.com/spring-projects/spring-security/issues/6804 (version 1.5.7
caused some compilation errors), in order to support Java 11.